name: Flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Flake8 and nbQA
      run: |
        python -m pip install --upgrade pip
        pip install flake8 nbqa

    - name: Lint Python files with Flake8
      run: |
        flake8 .

    - name: Lint Jupyter Notebooks with nbQA
      run: |
        nbqa flake8 .